### ISSUE TITLE
Setting up Initial Project Skeleton for the Angular SDK

### ISSUE THREAD

**Issue by JanithGan** [asgardio/asgardio-angular-oidc-sdk#5]
**Describe the solution you would prefer**

Setting up initial project skeleton for the SDK and samples, generated with [Angular CLI](https://github.com/angular/angular-cli).

**Tasks**

- [x] Create the workspace
- [x] Generate the library inside _lib_ folder
- [x] Generate sample app for basic usage inside _samples_ folder
- [x] Migrate from ts-lint to es-lint with [angular-eslint ](https://github.com/angular-eslint/angular-eslint)
- [x] Change package name to _**@asgardio/oidc-angular**_
- [x] Initialize _README_ file sketches for the SDK and the sample app
- [x] Add licence headers to all the applicable files
